# cloudbuild.yaml
# This file defines the continuous integration and deployment pipeline for the Go application.
# It builds a Docker container using a multi-stage Dockerfile and pushes it to Google Artifact Registry.
# This configuration is set to run the build and store the image in the Zurich, Switzerland region.

steps:
  # 1. Build and tag the Docker container image
  # This single step now handles the entire build process, including Go compilation,
  # as defined in the multi-stage Dockerfile.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_GCP_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
      - '.'
    id: 'Build-Image'

  # 2. Push the Docker image to Google Artifact Registry
  # This step pushes the final, small image created by the multi-stage Dockerfile
  # to the specified Artifact Registry repository in the Zurich region.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GCP_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
    id: 'Push-Image'

# Define the image(s) to be pushed to the registry upon successful build.
images:
  - '${_GCP_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'

# Define substitution variables. These allow for dynamic configuration at build time.
# _GCP_LOCATION is now set to the Zurich region.
substitutions:
  _GCP_LOCATION: 'europe-west6'
  _REPOSITORY: 'cloud-run-source-deploy'
  _IMAGE_NAME: 'go-workflow-dispatcher'

options:
  # Set the logging mode.
  logging: CLOUD_LOGGING_ONLY
  # Explicitly set the region where the build job itself will run.
  region: 'europe-west6'
